suggested: false
tech-preview: false
environments:
  - Test
  - Stage
stages:
  - name: Build Image
    description: creates a new version and then builds the image
  - name: Rollout to Stage
    description: stages the new version into the Stage environment
